### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by walmon** [Kommunicate-io/Kommunicate-Objective-C-Sample-App#3]
This https://docs.kommunicate.io/docs/cordova-pushnotification#ios document points here, incorrectly I believe. 

Ionic does not generate .swift files.

```
Open the project in XCode, Create new file with name KommunicateWrapper in YourApp/Classes. Copy the code for KommunicateWrapper from this link and paste it inside your newly created file.
```

That part does not specify the format of the new file, by entering this link https://docs.kommunicate.io/docs/cordova-pushnotification#ios one can assume it should be a `.swift` file however this is clearly a Objective-C sample not a Cordova one.

Also this 

```
Goto platforms/ios/YourApp/Classes and open AppDelegate.m file, if the file does not exist create one, add the below code in the file:
```

Does not specify where to get this value `"YOUR_TARGET_NAME_HERE-Swift.h"`

I would appreciate you point me to the right documentation or examples.

**Comment by mukeshthawani** [comment]
Thanks for sharing all the details. Ionic docs correctly points here because `KommunicateWrapper` file is required for the notifications. You don't have to use this sample app directly, just download and add this file in your project.

Format will be `swift`, same as the format of downloaded wrapper file. And yes you can generate `.swift` files in Ionic as we have done here in the [sample Ionic app](https://github.com/Kommunicate-io/Kommunicate-Ionic-Cordova-Sample-App/blob/master/ionic3/ionic-welcome/platforms/ios/KommunicateWrapper.swift).

When you open the project in Xcode, you will see the main app target and project name in the General section as [shown here](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/WorkingwithTargets.html).

**Comment by walmon** [comment]
Thanks @mukeshthawani  This project that you reference does not compile https://github.com/Kommunicate-io/Kommunicate-Ionic-Cordova-Sample-App/blob/master/ionic3/ionic-welcome/platforms/ios/KommunicateWrapper.swift so there's no way to see what changes need to be done in our own application. 

![image](https://user-images.githubusercontent.com/5282988/84702033-411ed300-af13-11ea-8f99-d801ac7d7cdb.png)

The reason why that project is important is because the instructions are not that clear so looking into an example is a great way to find out what's wrong.

**Comment by mukeshthawani** [comment]
@walmon We'll try the sample app and get back to you soon with an update.

**Comment by walmon** [comment]
Thanks @mukeshthawani this is the only thing stopping us from migrating from Intercom to your service. The Android part worked great!

**Comment by walmon** [comment]
Thanks @mukeshthawani this is the only thing stopping us from migrating from Intercom to your service. The Android part worked great!

**Comment by mukeshthawani** [comment]
We tried and it's working fine. Can you make sure you are opening `MyApp.xcworkspace` file?
Also, first clean the project(Xcode Product -> Clean) and then build.

**Comment by walmon** [comment]
First, a comment. This 
![image](https://user-images.githubusercontent.com/5282988/84929843-a26ab180-b08d-11ea-957a-eb0073833c18.png)
has incorrect instructions. `KommunicateWrapper` should not be copied in `YourApp/Classes`, it should be copied through XCODE to the root of the project.

However, I rolled back to before I added Kommunicate.

So before following this [Push Notifications instructions](https://docs.kommunicate.io/docs/cordova-pushnotification), I decided to just [add it](https://docs.kommunicate.io/docs/cordova-installation) to discard scenarios.

Without Kommunicate, my project runs fine. When I add Kommunicate and it starts to break other packages like this one (from XCODE):

![image](https://user-images.githubusercontent.com/5282988/84930103-07bea280-b08e-11ea-81d8-454952063869.png)

If I run it directly from the Ionic CLI it breaks as well

```
 CompileC /Users/walter/Library/Developer/Xcode/DerivedData/NeoClinic-gahybnihyiclrffnuptopwjeyllq/Build/Intermediates.noindex/NeoClinic.build/Debug-iphonesimulator/NeoClinic.build/Objects-normal/x86_64/FirebaseDynamicLinksPlugin.o /Users/walter/Development/neoclinic/neoclinic-app/app/platforms/ios/NeoClinic/Plugins/cordova-plugin-firebase-dynamiclinks/FirebaseDynamicLinksPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

If I remove Kommunicate, everything works again... Since the error is not directly on Kommunicate but is caused because of Kommunicate I don't how to handle this here.

Is this supposed to break without the Push Notifications steps? Or should it work without? I can either rollback to fully remove Kommunicate or continue and add the Push Notifications again.

**Comment by walmon** [comment]
I also noticed that since I added Kommunicate I get this:

```

[!] The `NeoClinic [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-NeoClinic/Pods-NeoClinic.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `NeoClinic [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-NeoClinic/Pods-NeoClinic.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `NeoClinic [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-NeoClinic/Pods-NeoClinic.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `NeoClinic [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-NeoClinic/Pods-NeoClinic.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by walmon** [comment]
Also, the working example is for Ionic 3. That may have something to do with this... 

There are a bunch of deprecated-warnings with the code that we copy and paste from your site and the library itself `KommunicateCordovaPlugin.swift`

![image](https://user-images.githubusercontent.com/5282988/84944054-760d6000-b0a2-11ea-9557-f8d781ac692e.png)

And there's this weird thing too.

![image](https://user-images.githubusercontent.com/5282988/84944244-af45d000-b0a2-11ea-8a0d-10686c1f2666.png)

**Comment by Samir1810** [comment]
> Also, the working example is for Ionic 3. That may have something to do with this...
> 
> There are a bunch of deprecated-warnings with the code that we copy and paste from your site and the library itself `KommunicateCordovaPlugin.swift`
> 
> ![image](https://user-images.githubusercontent.com/5282988/84944054-760d6000-b0a2-11ea-9557-f8d781ac692e.png)
> 
> And there's this weird thing too.
> 
> ![image](https://user-images.githubusercontent.com/5282988/84944244-af45d000-b0a2-11ea-8a0d-10686c1f2666.png)

Hi Walmon,

Let me ask Mukesh to take a look and update you.

**Comment by Samir1810** [comment]
Hi Walmon,

Let me ask Mukesh to take a look and update you.

**Comment by mukeshthawani** [comment]
Thanks for your suggestions. As those APIs were deprecated in the latest version, we'll be fixing those when we update the internal dependency. We've implemented some of your suggestions, and we'll do the same with the remaining ones. I hope everything is working now.
